### ISSUE TITLE
No content in the 2 zip files created by the powershell script.

### ISSUE THREAD

**Issue by liveolivier** [MicrosoftLearning/20486-DevelopingASPNETMVCWebApplications#1]
Hi,
I tried to create the materials for the updated labs of the 20486 MS Course. After executing the Powershell script without any error, 2 zip files have been created. The first Alffiles.zip is empty, the second one lab_instructions.zip contains an empty word document.

Is it too early?

Do I have to wait before an actual content is provided?

Thanks

**Comment by systemsymbiosis** [comment]
Same issue here. It would be great if the content was added for this course!

**Comment by barucht** [comment]
Hi,

this course's materials, although being fixed here in GH, are not yet released.
Formal release information will be published by MS LeX when the content is ready.

Thanks,
Baruch.

**Comment by systemsymbiosis** [comment]
Great thanks for the update.

**Comment by GerhardLiebenberg** [comment]
Hi.
The pondoc.ps1 file (in the Build folder) must be changed to retrieve the instructions from either the 20486B or 20486C subfolders.

The current scripts are: 
$docsInputDirectory = "..\Instructions\"
$docsOutputDirectory = $outputDirectory + "Lab Instructions\"

I changed it to:
$docsInputDirectory = "..\Instructions\20486C\"
$docsOutputDirectory = $outputDirectory + "Lab Instructions\20486C\"

This is the reason why the lab_instructions.zip file did not contain the correct documents.

Ps. A better way (instead of the hard-coded solution above) would be to prompt the user to indicate if the 20486B or 20486C documents should be used.
