### ISSUE TITLE
20486-DevelopingASPNETMVCWebApplications-master.zip --  is invalid

### ISSUE THREAD

**Issue by trapplayer** [MicrosoftLearning/20486-DevelopingASPNETMVCWebApplications#7]
GitHub Support: 
    I have downloaded the 20486-DevelopingASPNETMVCWebApplications-master.zip file successfully. When I 'right-click' on the file to 'Extract All' I get an error that **the zip files is invalid**. I tried it several times to be sure about the error, and it is the same every time. Please see screenshot provided:

![20486c-github-zipfile-error-122717](https://user-images.githubusercontent.com/11342259/34397763-e5f6fe36-eb46-11e7-8043-496ef0e73613.jpg)

Thanks for your expected help solving this issue.
A.J. Alfaro - MCT
12/27/17
20:45:00 hrs.
**************
*** still no one assigned to this issue as of Saturday 12/30/17 -- at 11:25 AM. 
*** zip file is still invalid ***
************* Please help, when you can -- class start date is approaching, Thank You...

**Comment by Dash** [comment]
Try using [7-Zip](http://www.7-zip.org/download.html) to extract instead.

**Comment by trapplayer** [comment]
Dash,
     It worked great! Why does the 20486 zip file require a different zip Extract program?
So I can explain it to the students, thanks again ...
A.J. Alfaro - MCT
01/02/18
16:53:00 hrs .. EST
********************
********************

**Comment by Dash** [comment]
Because Microsoft's bundled tools just aren't that fantastic.  And not all Zips are created equally.  It is likely that the compression used in this Zip was created by a tool that does it slightly differently than Windows expects.

Zip _should_ already be compatible, but it's an old format and people have improved it but at the cost of compatibility.
